# Generated by Django 5.1.2 on 2024-11-13 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=30, unique=True, verbose_name='nome da categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.FloatField(verbose_name='preço')),
                ('imagem', models.ImageField(upload_to='produtos/img')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('promocao', models.PositiveIntegerField(default=0, verbose_name='promoção')),
                ('categoria', models.ManyToManyField(to='produtos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_variacao', models.CharField(max_length=150, verbose_name='nome da variação')),
                ('imagem_variacao', models.ImageField(blank=True, null=True, upload_to='produtos/img', verbose_name='imagem da variação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
        migrations.CreateModel(
            name='Especificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=2)),
                ('preco', models.FloatField(verbose_name='preço')),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.variacao')),
            ],
            options={
                'verbose_name': 'Especificação',
                'verbose_name_plural': 'Especificações',
            },
        ),
    ]
