# Generated by Django 5.1.2 on 2024-11-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.AlterField(
            model_name='especificacao',
            name='variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificacoes', to='produtos.variacao'),
        ),
    ]
