# Generated by Django 5.1.2 on 2024-11-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_imagem_remove_produto_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacao',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0, verbose_name='preço'),
        ),
    ]
