# Generated by Django 5.1.2 on 2024-11-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_especificacao_preco_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(verbose_name='preço'),
        ),
    ]
