# Generated by Django 5.1.5 on 2025-02-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='variacao_nome',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
