# Generated by Django 5.1.5 on 2025-01-31 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0005_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacao_nome', models.CharField(max_length=150)),
                ('produto_nome', models.CharField(max_length=150)),
                ('tamanho', models.CharField(max_length=2)),
                ('slug', models.SlugField()),
                ('imagem', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
