# Generated by Django 5.1.5 on 2025-01-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('PD', 'Pendente'), ('CL', 'Cancelado')], default='PD', max_length=2),
        ),
    ]
