# Generated by Django 5.1.5 on 2025-02-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('PD', 'Pendente'), ('CL', 'Cancelado'), ('DV', 'Devolvido')], default='PD', max_length=2),
        ),
    ]
